### ISSUE TITLE
Missing upgrading guides for bitnami/harbor 13.x.x

### ISSUE THREAD

**Issue by lindhe** [bitnami/charts-docs#110]
Recently, version 13.0.0 of the bitnami/harbor chart was released: https://github.com/bitnami/charts/commit/dd74d96333a2e217394d4c6edd02dba818d79568

But [the upgrading notes](https://docs.bitnami.com/kubernetes/infrastructure/harbor/administration/upgrade/) mentions nothing about what steps needs to be performed when upgrading to this new breaking version.

**Comment by carrodher** [comment]
The following PR (https://github.com/bitnami/charts-docs/pull/109) added those changes in terms of code, but the website was not redeployed since the PR was merged, it should be redeployed sooner rather than later.

Thanks for letting us known.

**Comment by lindhe** [comment]
I see that it's redeployed now. That's good. However, I'm a bit confused about what the upgrading notes really achieve.

I see that, according to the notes, one should pin the database version when upgrading. But when inspecting the changes to the chart, it looks like the only breaking change introduced is a new database version. So what do we achieve by upgrading according  to the guide? :/

I'm feeling a bit confused about the intended upgrading roadmap for Harbor. Are we forever stuck at the database version used when first installing it?

**Comment by carrodher** [comment]
Following the upgrade notes, the PostgreSQL Helm chart is updated to the latest version of the Helm chart itself but overrides the container image to use the one from the previous PostgreSQL version.
Since the schema of the database changed between both versions, in order to upgrade the database pod/container from 11 to 13, you will need to follow the recommended path provided by PostgreSQL for this kind of data migration.
